### ISSUE TITLE
Example code needs to be updated I think.

### ISSUE THREAD

**Issue by mltbnz** [dbsystel/DBEmptyState#9]
`EmptyContentTableViewAdapter.hideSkeletonCellsWhenEmptyStateIsVisable` could not be found.

**Comment by lightsprint09** [comment]
Thanks for the hint. If you want you can go ahead and create a Pull Request with the fix included

**Comment by lightsprint09** [comment]
Seems like it was renamed to `EmptyContentTableViewAdapter.hideSkeletonCellsWhenEmptyStateIsVisable`

**Comment by lightsprint09** [comment]
I have checked the sample code. But is looks correct. What did you do, to get this `could not found` error

**Comment by mltbnz** [comment]
Ok. My bad. I was using an older version (0.2.1)
